import { execFileSync } from "node:child_process";
import { mkdtempSync,readFileSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe,expect,it } from "vitest";

describe("dados da dashboard gerencial",()=>{
  it("agrega clientes e atendimento sem persistir PII ou texto livre",()=>{const directory=mkdtempSync(join(tmpdir(),"mipo-manager-"));const customers=join(directory,"clientes.csv");const service=join(directory,"atendimento.csv");writeFileSync(customers,"customer_id,nome_completo,data_nascimento,renda_estimada,segmento_rfm,nivel_fidelidade,estado,dispositivo_principal,ltv_acumulado,total_pedidos_historico\nC1,Ana Teste,1990-01-01,5000,Campeões,Ouro,SP,Mobile,120.50,3\nC2,Bia Teste,1991-01-01,6000,Campeões,Ouro,SP,Mobile,80.00,1\n");writeFileSync(service,"ticket_id,customer_id,order_id,data_abertura,canal_entrada,categoria_problema,status_atendimento,texto_cliente,nota_csat,tempo_primeira_resposta_minutos,custo_operacional_ticket\nT1,C1,O1,2026-01-02,Chat,WISMO,Resolvido,onde está meu pedido,4,10,12.50\n");const output=JSON.parse(execFileSync(process.execPath,["scripts/import-management-data.mjs","--customers",customers,"--service",service],{encoding:"utf8"}));expect(output.customers).toEqual({read:2,groups:1,aggregated:2});expect(output.service.accepted).toBe(1);expect(output.service.wismo).toBe(1);expect(output.privacy).toEqual({rawCustomerRowsPersisted:0,freeTextPersisted:0,identifiersPersisted:0});});
  it("gera exatamente 600 eventos determinísticos em 90 dias",()=>{const run=()=>JSON.parse(execFileSync(process.execPath,["scripts/seed-dashboard-demo.mjs"],{encoding:"utf8"}));const first=run(),second=run();expect(first.eventCount).toBe(600);expect(first.horizonDays).toBe(90);expect(first.distribution).toEqual(second.distribution);expect(Object.values(first.distribution).every((value)=>Number(value)>=0)).toBe(true);});
  it("não inclui campos sensíveis nas tabelas gerenciais",()=>{const migration=readFileSync("supabase/migrations/202609160003_manager_dashboard_v2.sql","utf8");const tableDefinitions=migration.slice(0,migration.indexOf("alter table public.anonymous_sessions"));expect(tableDefinitions).not.toMatch(/nome_completo|data_nascimento|renda_estimada|texto_cliente|customer_id|order_id/);expect(migration).toContain("get_manager_dashboard");expect(migration).toContain("seed_version text default null");});
});
