"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { DashboardData, DashboardDecision, DashboardRow } from "@/src/domain/dashboard";

const riskLabel: Record<DashboardRow["risk"], string> = { size:"Tamanho", quality:"Qualidade", stock:"Estoque", none:"Sem intervenção", insufficient_evidence:"Evidência insuficiente" };
const decisionLabel: Record<DashboardDecision,string> = { accepted:"Aceita", kept_original:"Original mantida", not_required:"Não necessária", pending:"Pendente", abandoned:"Sem resposta" };
const date = new Intl.DateTimeFormat("pt-BR", { day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit" });
const percent = new Intl.NumberFormat("pt-BR", { style:"percent", maximumFractionDigits:1 });

function filteredMetrics(rows: DashboardRow[]) {
  const actionable=rows.filter((row)=>row.risk==="size"&&!!row.recommendedSize); const decided=actionable.filter((row)=>row.decision==="accepted"||row.decision==="kept_original"); const accepted=decided.filter((row)=>row.decision==="accepted").length;
  return { interventions:rows.length, actionable:actionable.length, decided:decided.length, accepted, pending:rows.filter((row)=>row.decision==="pending").length, abandoned:rows.filter((row)=>row.decision==="abandoned").length, acceptanceRate:decided.length?accepted/decided.length:null };
}

function Metric({ label, value, note, accent=false }: {label:string;value:string|number;note:string;accent?:boolean}) { return <article className={`metric ${accent?"metric--accent":""}`}><p>{label}</p><strong>{value}</strong><span>{note}</span></article>; }

export function MipoDashboard() {
  const [data,setData]=useState<DashboardData>(); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  const [period,setPeriod]=useState("all"); const [product,setProduct]=useState("all"); const [risk,setRisk]=useState("all"); const [decision,setDecision]=useState("all"); const [version,setVersion]=useState("all");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/dashboard",{cache:"no-store"});if(!response.ok)throw new Error((await response.json()).error??"Falha ao carregar painel.");setData(await response.json());}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao carregar painel.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const rows=useMemo(()=>{if(!data)return[];const cutoff=period==="all"?0:Date.now()-Number(period)*86400000;return data.rows.filter((row)=>(!cutoff||new Date(row.occurredAt).getTime()>=cutoff)&&(product==="all"||row.productId===product)&&(risk==="all"||row.risk===risk)&&(decision==="all"||row.decision===decision)&&(version==="all"||row.ruleVersion===version));},[data,period,product,risk,decision,version]);
  const metrics=useMemo(()=>filteredMetrics(rows),[rows]); const products=useMemo(()=>[...new Map((data?.rows??[]).map((row)=>[row.productId,row.product])).entries()],[data]); const versions=useMemo(()=>[...new Set((data?.rows??[]).map((row)=>row.ruleVersion))],[data]);
  const risks=useMemo(()=>Object.entries(riskLabel).map(([key,label])=>({key:key as DashboardRow["risk"],label,count:rows.filter((row)=>row.risk===key).length})).filter((item)=>item.count),[rows]); const maxRisk=Math.max(1,...risks.map((item)=>item.count));
  if(loading&&!data)return <main className="panel-state"><span className="panel-loader"/><h1>Organizando as evidências…</h1></main>;
  if(error)return <main className="panel-state"><p className="panel-kicker">Falha de leitura</p><h1>O painel não pôde ser carregado.</h1><p>{error}</p><button onClick={()=>void load()}>Tentar novamente</button></main>;
  if(!data)return null;
  const visibleRows=rows.slice(0,100);
  return <><a className="skip-link" href="#painel-conteudo">Pular para o conteúdo</a><main className="control-room" id="painel-conteudo">
    <header className="panel-header"><a href="/" className="panel-brand" translate="no">VÉRTICE <span>/ MIPO</span></a><div><p>Última leitura</p><time dateTime={data.generatedAt}>{date.format(new Date(data.generatedAt))}</time><button onClick={()=>void load()} disabled={loading}>{loading?"Atualizando…":"Atualizar"}</button></div></header>
    <section className="panel-intro"><div><p className="panel-kicker">Torre de controle · protótipo observável</p><h1>Decisões sob<br/><em>evidência.</em></h1></div><div className="panel-context"><p>Este painel mede somente interações registradas no protótipo. Não representa redução comprovada de devoluções ou economia capturada.</p><dl><div><dt>Base histórica</dt><dd>{data.historicalWindow.from?.slice(0,10)??"—"} → {data.historicalWindow.to?.slice(0,10)??"—"}</dd></div><div><dt>Amostra mínima</dt><dd>{data.minimumSampleSize} vendas por SKU</dd></div></dl></div></section>
    <section className="panel-filters" aria-label="Filtros"><label>Período<select value={period} onChange={(e)=>setPeriod(e.target.value)}><option value="all">Todo o período</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select></label><label>Produto<select value={product} onChange={(e)=>setProduct(e.target.value)}><option value="all">Todos</option>{products.map(([id,title])=><option value={id} key={id}>{title}</option>)}</select></label><label>Risco<select value={risk} onChange={(e)=>setRisk(e.target.value)}><option value="all">Todos</option>{Object.entries(riskLabel).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Decisão<select value={decision} onChange={(e)=>setDecision(e.target.value)}><option value="all">Todas</option>{Object.entries(decisionLabel).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Regra<select value={version} onChange={(e)=>setVersion(e.target.value)}><option value="all">Todas</option>{versions.map((item)=><option value={item} key={item}>{item}</option>)}</select></label></section>
    <section className="metrics-grid"><Metric label="Intervenções avaliadas" value={metrics.interventions} note="Todos os estados registrados"/><Metric label="Recomendações acionáveis" value={metrics.actionable} note="Com alternativa elegível"/><Metric label="Taxa de aceitação" value={metrics.acceptanceRate===null?"—":percent.format(metrics.acceptanceRate)} note={`${metrics.decided} decisões finais`} accent/><Metric label="Sem resposta" value={metrics.abandoned} note={`${metrics.pending} ainda pendentes`}/></section>
    <section className="agent-operations" aria-labelledby="agent-title"><div className="card-heading"><div><p className="panel-kicker">Operação da IA · separado de impacto</p><h2 id="agent-title">Agente ReAct</h2></div><span>{data.agent.total} execuções concluídas</span></div><div><Metric label="EloAgents" value={data.agent.eloagents} note="Provedor primário"/><Metric label="Groq" value={data.agent.groq} note="Fallback de modelo"/><Metric label="Fallback local" value={data.agent.deterministicFallback} note="Experiência preservada"/><Metric label="Cache / rejeições" value={`${data.agent.cacheHits} / ${data.agent.rejected}`} note={data.agent.averageLatencyMs===null?"Sem latência registrada":`Média ${data.agent.averageLatencyMs} ms`}/></div></section>
    <section className="panel-grid"><article className="panel-card funnel"><div className="card-heading"><div><p className="panel-kicker">Comportamento</p><h2>Funil de decisão</h2></div><span>Apenas recomendações acionáveis</span></div><div className="funnel-stack"><div style={{"--width":"100%"} as React.CSSProperties}><span>Avaliadas</span><strong>{metrics.interventions}</strong></div><div style={{"--width":metrics.interventions?`${Math.max(18,metrics.actionable/metrics.interventions*100)}%`:"18%"} as React.CSSProperties}><span>Acionáveis</span><strong>{metrics.actionable}</strong></div><div style={{"--width":metrics.interventions?`${Math.max(18,metrics.decided/metrics.interventions*100)}%`:"18%"} as React.CSSProperties}><span>Com decisão</span><strong>{metrics.decided}</strong></div><div className="accepted" style={{"--width":metrics.interventions?`${Math.max(18,metrics.accepted/metrics.interventions*100)}%`:"18%"} as React.CSSProperties}><span>Aceitas</span><strong>{metrics.accepted}</strong></div></div></article>
      <article className="panel-card"><div className="card-heading"><div><p className="panel-kicker">Distribuição</p><h2>Estados encontrados</h2></div></div>{risks.length?<div className="risk-bars">{risks.map((item)=><div key={item.key}><span>{item.label}</span><div><i style={{width:`${item.count/maxRisk*100}%`}}/></div><strong>{item.count}</strong></div>)}</div>:<Empty compact/>}</article></section>
    <section className={`simulator ${data.simulator.locked?"simulator--locked":""}`}><div><p className="panel-kicker">Cenário potencial</p><h2>Impacto só existe quando a evidência permite.</h2><p>{data.simulator.reason??"Há recomendações elegíveis. A parametrização financeira será habilitada em uma etapa controlada."}</p></div><span aria-hidden="true">{data.simulator.locked?"BLOQUEADO":"ELEGÍVEL"}</span></section>
    <section className="evidence-table"><div className="card-heading"><div><p className="panel-kicker">Rastreabilidade</p><h2>Intervenções recentes</h2></div><span>{rows.length} registros filtrados{rows.length>100?" · 100 mais recentes visíveis":""}</span></div>{rows.length?<div className="table-scroll"><table><caption className="sr-only">Intervenções MIPO filtradas</caption><thead><tr><th>Momento</th><th>Produto / escolha</th><th>Estado</th><th>Evidência</th><th>Decisão</th><th>Regra</th></tr></thead><tbody>{visibleRows.map((row)=><tr key={row.id}><td><time dateTime={row.occurredAt}>{date.format(new Date(row.occurredAt))}</time><small>#{row.id.slice(0,8)}</small></td><td><strong>{row.product}</strong><small>{row.selectedSize}{row.recommendedSize?` → ${row.recommendedSize}`:""}</small></td><td><span className={`risk-tag risk-tag--${row.risk}`}>{riskLabel[row.risk]}</span></td><td>{row.evidence}</td><td><span className={`decision decision--${row.decision}`}>{decisionLabel[row.decision]}</span></td><td><code>{row.ruleVersion}</code></td></tr>)}</tbody></table></div>:<Empty/>}</section>
  </main></>;
}

function Empty({compact=false}:{compact?:boolean}){return <div className={`panel-empty ${compact?"panel-empty--compact":""}`}><strong>Nenhuma interação neste recorte.</strong><p>Volte à loja, escolha um produto e execute um dos cenários do roteiro demonstrativo.</p><a href="/">Executar roteiro →</a></div>;}
