#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE="${MIPO_ENV_FILE:-.env.local}"
VERCEL_CLI=(npx --yes vercel@latest)

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 não está disponível. Instale-o e execute o wizard novamente."
    exit 1
  fi
}

vc() {
  "${VERCEL_CLI[@]}" "$@"
}

vc_in() {
  local directory="$1"
  shift
  (cd "$directory" && "${VERCEL_CLI[@]}" "$@")
}

set_vercel_env() {
  local directory="$1" key="$2" value="$3" visibility="$4" environment
  for environment in preview production; do
    if [[ "$visibility" == "secret" ]]; then
      printf '%s' "$value" | vc_in "$directory" env add "$key" "$environment" --force --yes --sensitive >/dev/null
    else
      printf '%s' "$value" | vc_in "$directory" env add "$key" "$environment" --force --yes --no-sensitive >/dev/null
    fi
    printf '  %s✓ configured%s %s → %s (%s)\n' "$GREEN" "$RESET" "$key" "$environment" "$visibility"
  done
}

banner "Deploy MIPO na Vercel"

stage "Publicar a branch main"
say "O deploy conectado ao Git usa a main remota como fonte."
require_command git
require_command curl
require_command openssl
step "Revise o estado atual abaixo."
git status --short --branch
if confirm "Publicar a main no origin agora?"; then
  git push origin main
else
  warn "Sem a main remota atualizada, a Vercel não verá esta configuração."
  pause "Publique a main manualmente e pressione Enter."
fi

stage "Criar e vincular o agente FastAPI"
say "Crie o primeiro projeto usando o mesmo repositório GitHub."
open_url "https://vercel.com/new"
step "Importe Bootcamp-EloGroup/mipo."
step "Defina Project Name como mipo-agent, Framework como FastAPI e Root Directory como services/agent."
step "Ainda não precisa adicionar variáveis; conclua a criação do projeto."
pause "Quando o projeto mipo-agent existir, pressione Enter."
ask VERCEL_AGENT_PROJECT "Nome exato do projeto do agente [mipo-agent]:"
VERCEL_AGENT_PROJECT="${VERCEL_AGENT_PROJECT:-mipo-agent}"
vc_in services/agent link --project "$VERCEL_AGENT_PROJECT"

stage "Configurar secrets e runtime do agente"
say "Os valores serão enviados diretamente à Vercel e também gravados em .env.local, que é ignorado pelo Git."
ask SUPABASE_URL "SUPABASE_URL:"
ask_secret SUPABASE_SECRET_KEY "SUPABASE_SECRET_KEY:"
ask_secret MIPO_PYTHON_AGENT_TOKEN "MIPO_PYTHON_AGENT_TOKEN (Enter gera um token forte):"
if [[ -z "$MIPO_PYTHON_AGENT_TOKEN" ]]; then
  MIPO_PYTHON_AGENT_TOKEN=$(openssl rand -hex 32)
fi
ask_secret ELOAGENTS_API_KEY "ELOAGENTS_API_KEY (opcional se usar Groq):"
ask_secret GROQ_API_KEY "GROQ_API_KEY (opcional se usar EloAgents):"
if [[ -z "$ELOAGENTS_API_KEY" && -z "$GROQ_API_KEY" ]]; then
  warn "Configure ao menos um provedor antes de ativar explicações por IA."
fi
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
write_env MIPO_PYTHON_AGENT_TOKEN "$MIPO_PYTHON_AGENT_TOKEN"
write_env ELOAGENTS_API_KEY "$ELOAGENTS_API_KEY"
write_env GROQ_API_KEY "$GROQ_API_KEY"
set_vercel_env services/agent SUPABASE_URL "$SUPABASE_URL" config
set_vercel_env services/agent SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY" secret
set_vercel_env services/agent MIPO_PYTHON_AGENT_TOKEN "$MIPO_PYTHON_AGENT_TOKEN" secret
set_vercel_env services/agent ELOAGENTS_BASE_URL "https://chat.eloagents.click/api" config
set_vercel_env services/agent ELOAGENTS_MODEL "gpt-54-mini" config
set_vercel_env services/agent GROQ_MODEL "openai/gpt-oss-20b" config
set_vercel_env services/agent AI_PROVIDER_TIMEOUT_MS "12000" config
set_vercel_env services/agent MIPO_AGENT_TOTAL_TIMEOUT_MS "30000" config
set_vercel_env services/agent MIPO_SEMANTIC_CACHE_TTL_SECONDS "300" config
[[ -n "$ELOAGENTS_API_KEY" ]] && set_vercel_env services/agent ELOAGENTS_API_KEY "$ELOAGENTS_API_KEY" secret
[[ -n "$GROQ_API_KEY" ]] && set_vercel_env services/agent GROQ_API_KEY "$GROQ_API_KEY" secret

stage "Publicar e validar o agente"
if confirm "Criar o deployment de produção do agente agora?"; then
  vc_in services/agent deploy --prod
else
  pause "Faça o deploy pelo painel e pressione Enter."
fi
open_url "https://vercel.com/dashboard"
step "Abra mipo-agent, copie o Production Domain HTTPS e remova a barra final."
ask MIPO_PYTHON_AGENT_URL "URL de produção do agente:"
MIPO_PYTHON_AGENT_URL="${MIPO_PYTHON_AGENT_URL%/}"
write_env MIPO_PYTHON_AGENT_URL "$MIPO_PYTHON_AGENT_URL"
step "Validando os endpoints públicos de saúde."
curl -fsS "$MIPO_PYTHON_AGENT_URL/health" >/dev/null
curl -fsS "$MIPO_PYTHON_AGENT_URL/ready" >/dev/null
say "Agente saudável."

stage "Criar e configurar a aplicação web"
open_url "https://vercel.com/new"
step "Importe novamente Bootcamp-EloGroup/mipo."
step "Defina Project Name como mipo-web, Framework como Next.js e Root Directory como ponto (raiz)."
pause "Quando o projeto mipo-web existir, pressione Enter."
ask VERCEL_WEB_PROJECT "Nome exato do projeto web [mipo-web]:"
VERCEL_WEB_PROJECT="${VERCEL_WEB_PROJECT:-mipo-web}"
vc link --project "$VERCEL_WEB_PROJECT"
set_vercel_env . DATA_SOURCE "supabase" config
set_vercel_env . NEXT_PUBLIC_DATA_SOURCE "supabase" config
set_vercel_env . MIPO_DEMO_MODE "true" config
set_vercel_env . SUPABASE_URL "$SUPABASE_URL" config
set_vercel_env . SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY" secret
set_vercel_env . AI_EXPLANATIONS_ENABLED "false" config
set_vercel_env . MIPO_PYTHON_AGENT_URL "$MIPO_PYTHON_AGENT_URL" config
set_vercel_env . MIPO_PYTHON_AGENT_TOKEN "$MIPO_PYTHON_AGENT_TOKEN" secret
set_vercel_env . MIPO_PYTHON_AGENT_TIMEOUT_MS "30000" config
set_vercel_env . MIPO_EXPERIMENT_ENABLED "false" config
write_env DATA_SOURCE "supabase"
write_env NEXT_PUBLIC_DATA_SOURCE "supabase"
write_env MIPO_DEMO_MODE "true"
write_env AI_EXPLANATIONS_ENABLED "false"
write_env MIPO_PYTHON_AGENT_TIMEOUT_MS "30000"
write_env MIPO_EXPERIMENT_ENABLED "false"

stage "Publicar, validar e ativar a IA"
if confirm "Publicar a aplicação web em produção com IA desativada?"; then
  vc deploy --prod
else
  pause "Faça o deploy pelo painel e pressione Enter."
fi
open_url "https://vercel.com/dashboard"
step "Abra mipo-web e copie o Production Domain HTTPS, sem barra final."
ask MIPO_WEB_URL "URL de produção da aplicação:"
MIPO_WEB_URL="${MIPO_WEB_URL%/}"
curl -fsS "$MIPO_WEB_URL/api/health" >/dev/null
curl -fsS "$MIPO_WEB_URL/api/products" >/dev/null
curl -fsS "$MIPO_WEB_URL/api/dashboard?origin=all" >/dev/null
say "Fluxo determinístico validado."
if [[ -n "$ELOAGENTS_API_KEY" || -n "$GROQ_API_KEY" ]]; then
  if confirm "Ativar explicações por IA e publicar novamente?"; then
    set_vercel_env . AI_EXPLANATIONS_ENABLED "true" config
    write_env AI_EXPLANATIONS_ENABLED "true"
    vc deploy --prod
    say "Abra a loja e valide uma explicação, o concierge e a auditoria da sacola."
    open_url "$MIPO_WEB_URL"
  fi
fi
say "MIPO_EXPERIMENT_ENABLED permanece false até a aprovação formal do piloto."

finish
